[core]
reloadable = true
order = 0

[package]
version = "1.0.0"
category = "Simulation"
title = "RBWheeledRobotExample"
description = ""
authors = ["NVIDIA"]
repository = ""
keywords = []
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"


[dependencies]
"omni.kit.uiapp" = {}
"omni.isaac.ui" = {}
"omni.isaac.core" = {}

[[python.module]]
name = "RBWheeledRobotExample_python.WheeledRobotLimoDiff"

[[python.module]]
name = "RBWheeledRobotExample_python.WheeledRobotLimoDiffROS2"

[[python.module]]
name = "RBWheeledRobotExample_python.WheeledRobotLimoAckermannROS2"

[[python.module]]
name = "RBWheeledRobotExample_python.WheeledRobotLimoAckermannTwistROS2"

[[python.module]]
name = "RBWheeledRobotExample_python.WheeledRobotsKaya"

[[python.module]]
name = "RBWheeledRobotExample_python.WheeledRobotSummit"

[[python.module]]
name = "RBWheeledRobotExample_python.WheeledRobotSummitO3Wheel"

[[python.module]]
name = "RBWheeledRobotExample_python.WheeledRobotSummitO3WheelROS2"
